### PR TITLE
Bump ember-css-modules & fix regression

### LINKED ISSUE #200: Addon does not work with ember-cli 3.0.0(-beta.2)
I have created a sample application [here](https://github.com/jacobq/ecn-with-ecli-3.x) that demonstrates the problem. The error looks like this in this case:

```
Uncaught Error: Could not find module `ember-cli-notifications/styles/components/notification-container` imported from `ember-cli-notifications/components/notification-container`
```

It seems to be related to [this line](https://github.com/stonecircle/ember-cli-notifications/blob/master/addon/components/notification-container.js#L5):
```javascript
import styles from '../styles/components/notification-container';
```
If I comment that line out and replace it with `const styles = {}` or create the file `../styles/components/notification-container.js` this error goes away.

### LINKED ISSUE #202: Need to fix regression from #2f181d31 (breaks when environment variables not present)
Commit https://github.com/stonecircle/ember-cli-notifications/commit/2f181d31d3d4d1b498900f398aebeda085f773de introduces a rather nasty regression wherein users will encounter an error (`Error: Assertion Failed: Cannot call get with 'clearDuration' on an undefined object`) unless they define `ember-cli-notifications` settings in their application's configuration. e.g.
```javascript
// config/environment.js
...
    const ENV = {
...
        'ember-cli-notifications': {
            // includeFontAwesome: true,
            // autoClear: false,
            // clearDuration: 2400
        },
...
```

The [culprit is here](https://github.com/stonecircle/ember-cli-notifications/commit/2f181d31d3d4d1b498900f398aebeda085f773de#diff-48106eb91c481ba31b7f2bf8cdb486d7R5) where `globals` may be assigned `undefined` meanwhile below it is assumed to be valid when passed to `getWithDefault`.

### PR DESCRIPTION
**Pull request by jacobq**
fix: Prevent error when environement settings aren't defined

* Fixes [regression](https://github.com/stonecircle/ember-cli-notifications/commit/2f181d31d3d4d1b498900f398aebeda085f773de#diff-48106eb91c481ba31b7f2bf8cdb486d7R5) related to calling `getWithDefault(undefined, ...)` (Closes #202)
* Eliminates `ember-get-config` in favor of `Application.lookup('config:environment')` (to make testable)
* Updates ember-css-modules to v0.7.7 to work with beta versions of ember-cli (closes #200) 
  See https://github.com/salsify/ember-css-modules/pull/95
* Updates `ember-cli` from 2.16 to 2.18 via [`ember-cli-update`](https://github.com/kellyselden/ember-cli-update) (just for the heck of it)

### CODE REVIEW

**Comment by jacobq** [comment]
BTW, CI failure appears to be caused by https://github.com/romulomachado/ember-cli-string-helpers/pull/19

**Comment by jacobq** [comment]
Closes #202

**Comment by jacobq** [comment]
@mansona Please let me know if you would like me to squash these commits or make any other changes. I'd love it if this could get merged and released soon.

**Comment by jacobq** [comment]
The ecsh node 4.x thing is fixed now so I will adjust this PR later today to unpin.
https://github.com/romulomachado/ember-cli-string-helpers/pull/19#event-1464483518

**Comment by jacobq** [comment]
:rocket:

**Review by hiimtaylorjones — APPROVED** [review]

**Comment by lamabiker** [comment]
Any news on this PR? Thanks guys

**Comment by mansona** [comment]
Howdy folks 👋 

Sorry for the delay but this has now been fixed in https://github.com/stonecircle/ember-cli-notifications/pull/197

I was hoping to get your PR merged @jacobq but the existing PR was staring the testing game for ember-cli-notifications and I didn't want to upgrade without making sure that we didn't break anything for all versions of Ember we support.

I will be more active here now so I will be more responsive on PRs and issues, so don't give up if you want to contribute 😉

**Pull request closed without merging**
