### PR TITLE
Feature/font awesome 5

### PR DESCRIPTION
**Pull request by basz**
attempt at #206

### CODE REVIEW

**Comment by basz** [comment]
Ping! Is this project dead?

**Comment by donaldwasserman** [comment]
@basz I'd also like to know that. I'd be happy to maintain this with some enhancements. Maybe this is something that we can add to the ember-adopted addons project?

I'm `donaldwasserman` on discord if you'd want to chat more about it. 

I use this in work projects and am currently maintaining two separate ways of dealing with this same problem and would like to not to do that.

**Comment by basz** [comment]
Guess that’s up to @ynnoj (ping)

He seems active enough but probably doesn’t have the time currently to maintain this repo.

**Comment by donaldwasserman** [comment]
@ynnoj This is a really great addon, but the issues are really piling up. I'd really like to help maintain this if you don't have enough bandwidth!

**Comment by ynnoj** [comment]
@donaldwasserman Hey! Would love to get you involved with steering the project and working on some ideas I've had.

How do we do this?

**Comment by NullVoxPopuli** [comment]
This works for me! 

Just had to add:

```ts
  ENV['ember-cli-notifications'] = {
    icons: 'fa-5',
  };
```
to my config/environment file

**Comment by juggy** [comment]
This does not work on 3.12+. Removing the `tagName: ''` line makes it work. with no apparent UI problems.

**Comment by NullVoxPopuli** [comment]
@juggy, I'm using this branch on 3.13+ https://github.com/ynnoj/ember-cli-notifications/pull/246

**Comment by mansona** [comment]
Hey folks 👋 just an update on this PR, we have wanted to make this a dependency-free addon for quite a while so we have removed Font Awesome as a necessary dependency and included SVGs for the icons instead. You can take a look at the upcoming release here https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340

I am really interested in knowing what you all think about this change

**Pull request closed without merging**
