### PR TITLE
Resolve Mouse Event Deprecations

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
... by updating things

Additionally, because _I_ need font awesome 5, I've merged in the font awesome 5 branch: https://github.com/ynnoj/ember-cli-notifications/pull/239

Thanks, @basz!

### CODE REVIEW

**Comment by mansona** [comment]
Hey @NullVoxPopuli 👋 I've taken back over this addon so  I'm trying to get through the backlog of issues and PRs

This PR is a bit big and it's hard to see where the actual change is 🙈 I'm working on the new version of the addon here https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 so maybe you could help get rid of these deprecations once it's released?

**Comment by NullVoxPopuli** [comment]
Awesome! 

And I think I just upgraded stuff here ? :shrug:

**Comment by mansona** [comment]
so... it looks like it's more than just an upgrade 🤔 you seem to be using the `{{on}}` modifier and an action to get around the deprecations to do with mouse events 🤔 

Maybe we can worry about adding that change when the other PR is merged 😂 Also do we know if there is a polyfill for the on modifier that works back to Ember 2.12?

**Comment by NullVoxPopuli** [comment]
Sounds good!

2.18 is as far back as this goes: https://github.com/buschtoens/ember-on-modifier/blob/master/README.md

**Comment by mansona** [comment]
Awesome 🎉that's a great find. I don't suppose you could create a PR for me sometime next week when the other PR is merged?

**Comment by NullVoxPopuli** [comment]
Yeah, We'll see if I remember!

**Comment by mansona** [comment]
Hey @NullVoxPopuli any chance you can update this PR? things have changed a lot now that https://github.com/mansona/ember-cli-notifications/pull/251 is merged 😂

**Comment by NullVoxPopuli** [comment]
I totally forgot about this. lol.

I'll take a look next time I have open source time!

**Comment by mansona** [comment]
@NullVoxPopuli sounds good! It might be a lot easier now that the addon has been properly updated 😂 and you could even just do a new PR 🤔 

Should we close this one for now?

**Comment by mansona** [comment]
This was fixed in #263 🎉

**Pull request closed without merging**
