### PR TITLE
fixing sass syntax in css

### PR DESCRIPTION
**Pull request by mansona**

### CODE REVIEW

**Comment by ynnoj** [comment]
@mansona Could this be related to #146?

We will need to refactor the CSS rule, rather than just remove it.

**Comment by mansona** [comment]
@ynnoj yes it could have something to do with it. I saw some **serious** issues with CSS in dev mode where it seemed like the sourcemaps were claiming that **all** CSS in the entire app were "owned" by that `notification-message.css` file. 

Apart from anything else, this is currently preventing anyone build any of their apps in production mode because of the following: 

```
clean-css dangerously ignores these errors but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
```

so my opinion is that we merge and release this fix and then worry about fixing it properly because of the seriousness of the issue. I don't have the skill/understanding to "refactor the CSS rule" but I might check if I can make it so that Travis fails if something like this comes up again.

**Comment by jurgenwerk** [comment]
Thanks @mansona, I managed to fix my suddenly-failing production build with your patch.

**Comment by ynnoj** [comment]
This _should_ be fixed in `4.1.7` which I just published.

**Pull request closed without merging**
