### PR TITLE
Added support for SVG icons

### PR DESCRIPTION
**Pull request by theenadayalank**
Now we can able to use SVG icons instead of font icons.

### CODE REVIEW

**Comment by mansona** [comment]
@theenadayalank thanks for the PR 🎉 

I have laid out a vision for this addon in this comment https://github.com/stonecircle/ember-cli-notifications/pull/185#issuecomment-382873190 but I thought I would respond to your PR directly.

I want this PR to land (eventually). It's currently not the best experience for devs when they install ember-cli-notifications and it doesn't work out of the box because you need font-awesome configuration. I want to move to SVG as the default with font-awesome or bootstrap as optional.

There are a few points on on the PR and how we might need to proceed:

- making this the default will require a major version bump. I have no objection (integers are cheap) but we might batch it together with a few other things that we want to move around at a major bump
- Where did you get these Icons? I am happy to use them but we need to make sure the copyright is ok 👍 also can you share an image of what this looks like as a comparison please
-  I am not likely to add inline-svg as a dependency as you can use SVG directly in Ember. I would recommend [this awesome talk by Jen Weber](https://www.youtube.com/watch?v=ZC3lD_DFlkc) that taught me how to do SVG aweseomely in Ember 💪 

I hope this is useful in some way 😖

**Comment by theenadayalank** [comment]
Thank you @mansona for your great suggestions🙂. Sorry for the delay in getting back to you. 

The talk by Jen Weber about inlining SVG in ember gave me a lot more insights to handle SVGs😉. The icons I used are downloaded from [ material.io ](https://material.io/tools/icons). Yes, they are open sourced icons.

I will change the code as per the suggestions you have given and will let you know once I finish the changes💪.

**Comment by theenadayalank** [comment]
I have pushed my changes. Kindly review the PR and do the needful 🙂
@ynnoj

**Comment by mansona** [comment]
Hey @theenadayalank, me again 😂 

Sorry for the delay but I have actually included your change in https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 and actually made it the default and **only** icons for this addon 😱 

I also cherry-picked your change so you got the credit in the PR 🎉 thanks again for your contribution and sorry for taking so long to get it sorted

**Pull request closed without merging**
