### PR TITLE
Allow global values to be defined in app config

### LINKED ISSUE #101: Global config in environment.js?
Why not config in environment except for the fonts?

Maybe it's useful to have these configurable:

```
autoClear: true,
clearDuration: 3000,
successMessage: 'Something',
includeFontAwesome,
icons,
etc...
```

No?

### PR DESCRIPTION
**Pull request by ynnoj**
User configurable properties `autoClear` and `clearDuration` can now be set in consuming app config. 

Fixes #101.

### CODE REVIEW

**Comment by rinoldsimon** [comment]
When this issue will be resolved ?

**Comment by ynnoj** [comment]
@rinoldsimon This is not really an _issue_ so to speak (nothing is broken). But hopefully I'll have some time this week to finish it off.

**Comment by rinoldsimon** [comment]
now this will work with the version "4.0.9" ?

**Comment by ynnoj** [comment]
@rinoldsimon No. I need to publish a new major version (`5.0.0`) as this is a breaking change. I also want to fix #102 as a part of that release too.

**Comment by viacommits** [comment]
Is this in the latest 4.2.0 on NPM?  I had to point my package.json to the Github master to get this to work

**Comment by ynnoj** [comment]
@zeiv No, it's a breaking change so will be a major release.

**Comment by viacommits** [comment]
@ynnoj Gotcha, thanks.  I saw you took it off of the 5.0.0 milestone so I wasn't sure.  Love the addon by the way, _way_ better than flashes.

**Comment by ynnoj** [comment]
@zeiv That is awesome to hear, thank you! We'll keep working toward that `5.0.0` release 🎉

**Comment by rinoldsimon** [comment]
should we wait until 5.0.0 release to use `autoClear` and `clearDuration` properties in app config?

**Pull request merged**
