### PR TITLE
autoClear precedence

### PR DESCRIPTION
**Pull request by adrianricardo**
autoClear option should take precedence over global default autoClear

### CODE REVIEW

**Comment by mansona** [comment]
hey @adrianricardo thanks for this catch, it is an edge case that we hadn't considered :tada: 

one small comment and then we'll merge your PR, can you convert this to a 1 line change using the [ternary Operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) please? 

Thanks :+1:

**Comment by mansona** [comment]
Also when you re-submit it can you please rebase on master instead of merging, that will make this a single change instead of including a merge commit: https://cloudup.com/cce9NHJ4OTU

**Comment by ynnoj** [comment]
@adrianricardo Please also pin jQuery to `1.11.3` in `bower.json`, that will fix the failing Travis build. Thanks.

**Comment by adrianricardo** [comment]
Yes! I will get to this! And definitely will do @mansona. That is usually my approach but I was trying the github mac app for the first time and I guess the big "sync" button defaults to a merge rather than rebase? Back to sourcetree!

**Comment by mansona** [comment]
Hmm... I'm not too sure sourcetree allows you to force push (which you will need to do) so that this will work the way you need it to. If you're not used to rebasing and force pushing (this can break things) I would suggest that you just make a clean new branch and make the required changes there and make a new PR.

Just my 2c

**Comment by adrianricardo** [comment]
here we go, https://github.com/stonecircle/ember-cli-notifications/pull/77

**Pull request closed without merging**
